let MyDate=new Date();
console.log(MyDate.toString())
console.log(MyDate.toDateString())
console.log(MyDate.toTimeString())
console.log(MyDate.toLocaleDateString())
console.log(MyDate.toLocaleString())
console.log(MyDate.toLocaleTimeString())
console.log(MyDate.toJSON())
console.log(MyDate.toISOString())
console.log(MyDate.toUTCString())